"""add timestamps

Revision ID: 20231109_1349
Revises: 20231109_1346
Create Date: 2023-11-09 13:50:10.054024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20231109_1349'
down_revision: Union[str, None] = '20231109_1346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('department', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('employee', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('employee', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('employee', 'updated_at')
    op.drop_column('employee', 'created_at')
    op.drop_column('department', 'updated_at')
    op.drop_column('department', 'created_at')
    # ### end Alembic commands ###
